name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  php:
    name: 'Sylius ${{ matrix.sylius }} / PHP ${{ matrix.php }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
          - 8.3
        sylius:
          - 1.12.0
          - 1.13.0
          - 1.14.0
    env:
      SYMFONY_ARGS: --no-tls
      COMPOSER_ARGS: --prefer-dist
      DOCKER_INTERACTIVE_ARGS: -t

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gd, intl, json
          ini-values: date.timezone=UTC
          tools: symfony-cli

      - name: Set project php-version
        run: |
          echo "${{ matrix.php }}" > .php-version

      - name: Determine composer cache directory
        id: composer-cache-directory
        run: echo "directory=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        id: cache-composer
        with:
          path: ${{ steps.composer-cache-directory.outputs.directory }}
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - name: Ensure that composer cache directory exists
        run: mkdir -p ${{ steps.composer-cache-directory.outputs.directory }}

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ secrets.GITHUB_TOKEN }}

      - run: 'make install -e SYLIUS_VERSION=${{ matrix.sylius }}'
     
      - run: make test.composer

      - run: make test.schema

      - run: make test.phpunit
